const BOOK = {
  meta:{
    badge:"연플래닝 한글 깨우기 001 · 초등 1·2학년",
    title:"ㄱㄴㄷ 친구들이 깨어났어요",
    sub:"잠자던 자음들이 눈을 뜨고 이름을 찾아가는 이야기",
    badge_en:"Yeon Planning · Hello Hangeul 001 · Grades 1–2",
    title_en:"The Hangeul Letters Wake Up",
    sub_en:"Sleeping Korean letters open their eyes and learn their names"
  },
  pages:[
    {
      label:"고요한 밤",
      line:"깜깜한 밤, 도서관은 쌔근쌔근 잠이 들었어요.\n책장 맨 끝, 먼지 쌓인 상자 하나가 살짝 들썩였어요.",
      label_en:"A Quiet Night",
      line_en:"In the dark, dark night, the library was fast asleep.\nAt the end of a shelf, a dusty old box gave a little shake.",
      art:"generic"
    },
    {
      label:"첫 번째로 깬 ㄱ",
      line:"“으으, 잘 잤다!”\n맨 처음 눈을 뜬 건 둥글게 굽은 ㄱ이었어요.\n“내 이름이 뭐였더라? 기윽… 기역!”",
      label_en:"ㄱ Wakes Up First",
      line_en:"‘Mmm, what a good sleep!’\nThe first to open its eyes was ㄱ, bent like a little hook.\n‘What was my name again? Gi… Giyeok! And I make the g sound.’",
      art:"generic"
    },
    {
      label:"기지개 켜는 ㄴ",
      line:"ㄱ이 콕 찌르자 옆에 있던 ㄴ도 부스스 일어났어요.\n“나는 니은! 누울 때 폭신한 침대처럼 생겼지.”\nㄴ은 길게 기지개를 켰어요.",
      label_en:"ㄴ Has a Big Stretch",
      line_en:"ㄱ gave a little poke, and sleepy ㄴ sat up too.\n‘I am Nieun, and I make the n sound! I look like a comfy bed.’\nㄴ stretched long and wide.",
      art:"generic"
    },
    {
      label:"두 친구가 만든 말",
      line:"ㄱ과 ㄴ이 손을 잡으니 작은 소리가 났어요.\n“가… 나… 어? 우리가 붙으면 말이 되네!”\n둘은 까르르 웃었어요.",
      label_en:"Two Friends Make a Word",
      line_en:"ㄱ and ㄴ held hands, and a tiny sound popped out.\n‘Ga… na… oh! When we join, we make a word!’\nThe two friends giggled and giggled.",
      art:"generic"
    },
    {
      label:"문을 여는 ㄷ",
      line:"덜컹덜컹, 상자 문이 열리고 ㄷ이 나왔어요.\n“나는 디귿! 문처럼 한쪽이 열려 있단다.”\nㄷ이 문을 활짝 열자 친구들이 우르르 쏟아졌어요.",
      label_en:"ㄷ Opens the Door",
      line_en:"Rattle, rattle — the box opened, and out came ㄷ.\n‘I am Digeut, and I make the d sound! One side of me is open, like a door.’\nㄷ flung the door wide, and more friends came tumbling out.",
      art:"generic"
    },
    {
      label:"노래하는 ㄹ",
      line:"구불구불 ㄹ이 춤추듯 나왔어요.\n“리을! 리을! 나는 노래를 좋아해.”\n랄랄라, 도서관에 작은 노랫소리가 퍼졌어요.",
      label_en:"ㄹ Loves to Sing",
      line_en:"Wiggly ㄹ came out dancing this way and that.\n‘Rieul! Rieul! I make the r and l sound, and I love to sing.’\nLa la la — a little song floated through the library.",
      art:"generic"
    },
    {
      label:"산처럼 든든한 ㅁ ㅂ ㅅ",
      line:"네모난 ㅁ은 미음, 입처럼 야무졌어요.\n주머니 닮은 ㅂ은 비읍, 보물을 담았지요.\n뾰족한 ㅅ은 시옷, 산처럼 우뚝 섰어요.",
      label_en:"Strong Friends ㅁ ㅂ ㅅ",
      line_en:"Square ㅁ is Mieum (m), neat and tidy like a mouth.\nPocket-shaped ㅂ is Bieup (b), keeping treasure inside.\nPointy ㅅ is Siot (s), standing tall like a mountain.",
      art:"generic"
    },
    {
      label:"동그란 ㅇ의 등장",
      line:"데굴데굴 동그란 ㅇ이 굴러왔어요.\n“이응! 나는 아무 소리 없이 자리를 지켜.\n그래도 ‘아, 야, 어’ 모두 내 품에서 시작한단다.”",
      label_en:"Round ㅇ Rolls In",
      line_en:"Round ㅇ came rolling in, round and round.\n‘I am Ieung! At the front I stay quiet and make no sound.\nBut ah, ya, eo — every one of them begins with me.’",
      art:"generic"
    },
    {
      label:"마지막 친구들 ㅈ ㅊ ㅋ ㅌ ㅍ ㅎ",
      line:"지읒, 치읓, 키읔, 티읕, 피읖, 히읗!\n남은 친구들이 줄줄이 깨어나 인사했어요.\n이제 자음 친구들이 모두 모였어요.",
      label_en:"The Last Friends ㅈ ㅊ ㅋ ㅌ ㅍ ㅎ",
      line_en:"Jieut (j), Chieut (ch), Kieuk (k), Tieut (t), Pieup (p), Hieut (h)!\nThe last friends woke up, one after another, and said hello.\nNow all the consonant friends were here together.",
      art:"generic"
    },
    {
      label:"이름을 잃어버렸어요",
      line:"그런데 ㅎ이 울먹였어요.\n“우리… 이름은 알겠는데, 어디로 가야 하지?”\n친구들은 서로 얼굴만 바라보았어요.",
      label_en:"Where Do We Belong?",
      line_en:"But then ㅎ began to sniffle.\n‘We know our names… but where are we supposed to go?’\nThe friends just looked at one another.",
      art:"generic"
    },
    {
      label:"잠든 아이의 책상",
      line:"그때 ㅇ이 창가를 가리켰어요.\n“저기, 글자를 배우다 잠든 아이가 있어!”\n공책에는 삐뚤빼뚤 쓰다 만 글자들이 가득했어요.",
      label_en:"A Sleeping Child's Desk",
      line_en:"Then ㅇ pointed toward the window.\n‘Look — a child fell asleep while learning letters!’\nThe notebook was full of wobbly, half-finished writing.",
      art:"generic"
    },
    {
      label:"한 글자씩 살며시",
      line:"자음 친구들은 살금살금 공책으로 갔어요.\nㄱ은 ‘가’ 자리에, ㄴ은 ‘나’ 자리에 쏙.\n빈 칸들이 하나둘 채워졌어요.",
      label_en:"One Gentle Letter at a Time",
      line_en:"On tiptoe, the friends crept to the notebook.\nㄱ slipped into ‘ga,’ ㄴ slipped into ‘na.’\nOne by one, the empty boxes were filled.",
      art:"generic"
    },
    {
      label:"아이가 깨어나요",
      line:"아침 햇살에 아이가 눈을 떴어요.\n“어? 내 공책이 다 채워졌네!”\n글자들이 반짝반짝 웃고 있는 것 같았어요.",
      label_en:"The Child Wakes Up",
      line_en:"In the morning sunlight, the child opened both eyes.\n‘Huh? My notebook is all filled in!’\nThe letters seemed to sparkle and smile.",
      art:"generic"
    },
    {
      label:"함께 읽는 첫 글",
      line:"아이는 손가락으로 글자를 짚으며 읽었어요.\n“가… 나… 다… 라…”\n자음 친구들도 마음속에서 조용히 따라 읽었어요.",
      label_en:"Reading the First Words Together",
      line_en:"The child read along, tapping each letter with a finger.\n‘Ga… na… da… ra…’\nDeep inside, the friends quietly read along too.",
      art:"generic"
    },
    {
      label:"다시 책 속으로",
      line:"“이제 너는 우리 이름을 알지?”\n친구들은 빙긋 웃으며 책 속으로 돌아갔어요.\n언제든 부르면 다시 깨어날 준비를 하고요.",
      label_en:"Back Into the Book",
      line_en:"‘Now you know our names, don't you?’\nWith a gentle smile, the friends slipped back into the book.\nReady to wake again, anytime you call.",
      art:"generic"
    },
    {
      label:"너의 차례야",
      line:"자, 이번엔 네 차례예요.\nㄱ부터 ㅎ까지, 천천히 불러 볼까요?\n네가 부르면 자음 친구들이 또 깨어날 거예요.",
      label_en:"Now It's Your Turn",
      line_en:"Now it's your turn.\nShall we call them slowly, from ㄱ all the way to ㅎ?\nWhen you call, the letter friends will wake up again.",
      art:"generic"
    }
  ],
  message:"글자를 하나씩 알아 가면, 세상의 이야기가 내게 말을 걸어와요.",
  message_en:"Once you know your letters one by one, the whole world begins to tell you its stories.",
  grow:{
    theme:"한글 자음 — 글자와 친구가 되는 첫걸음",
    desc:"ㄱ부터 ㅎ까지 열네 자음을 모양·이름·소리로 자연스럽게 만나게 합니다. 글자를 ‘공부 대상’이 아니라 ‘깨워 주고 싶은 친구’로 느끼게 해 읽기에 대한 두려움을 줄여 줍니다.",
    grade:"초1·2 · 약 5분",
    theme_en:"The Korean Consonants — a first step toward making friends with letters",
    desc_en:"This story introduces the fourteen Korean consonants, from ㄱ to ㅎ, through their shapes, names, and sounds. Young readers meet each letter not as something to ‘study,’ but as a sleepy friend they get to wake up — which makes learning to read feel warm and friendly instead of scary.",
    grade_en:"Grades 1–2 · about 5 minutes"
  },
  activityByGrade:{
    "초1~2":[
      "ㄱ, ㄴ, ㄷ을 손가락으로 허공에 그려 볼까요?",
      "내 이름에는 어떤 자음 친구가 숨어 있나요?",
      "ㅇ(이응)처럼 동그란 물건을 방에서 하나 찾아보세요."
    ],
    "초3~4":[
      "ㄱ과 ㅏ를 합치면 ‘가’가 돼요. 다른 자음으로 ‘□ㅏ’를 세 개 만들어 보세요.",
      "자음 친구들이 ‘모양’을 닮은 물건을 각각 떠올려 적어 보세요. (예: ㅁ-창문)",
      "이야기에서 가장 마음에 든 자음 친구와 그 까닭을 말해 보세요."
    ],
    "초5~6":[
      "자음 14개를 모두 쓰고, 각 글자로 시작하는 낱말을 하나씩 적어 보세요.",
      "‘글자를 안다는 것’이 왜 중요한지 두세 문장으로 써 보세요.",
      "내가 자음 친구라면 어떤 모양·성격일지 새 캐릭터로 만들어 보세요."
    ]
  },
  activityByGrade_en:{
    "Grade 1-2":[
      "Draw the shapes of ㄱ (Giyeok), ㄴ (Nieun), and ㄷ (Digeut) in the air with your finger.",
      "ㅇ (Ieung) is round like a circle. Find one round thing in your room.",
      "Say the sounds out loud: ㄱ is ‘g,’ ㄴ is ‘n,’ ㄷ is ‘d.’ Can you make each sound?"
    ],
    "Grade 3-4":[
      "ㄱ plus the vowel ㅏ makes ‘ga.’ Add ㅏ to ㄴ and ㄷ — what two words do you make?",
      "Each letter looks like something. ㅁ looks like a window. Draw what ㄴ and ㅅ remind you of.",
      "Which letter friend did you like best, and why? Tell someone in one or two sentences."
    ],
    "Grade 5-6":[
      "Korean has 14 basic consonants. List as many as you can with their names (Giyeok, Nieun…).",
      "How is the Korean alphabet different from the English ABCs? Write two or three sentences.",
      "If you were a letter that could wake up, what shape and personality would you have? Invent a character."
    ]
  },
  future:[
    "글자를 알면 어떤 새로운 일을 할 수 있을까요?",
    "만약 자음 친구가 한 명도 깨어나지 못했다면 세상은 어떻게 달라졌을까요?",
    "다음에는 모음 친구들(ㅏ, ㅓ, ㅗ…)이 깨어난다면 어떤 이야기가 펼쳐질까요?"
  ],
  future_en:[
    "Once you can read, what new things will you be able to do?",
    "What if not a single letter friend had woken up? How would the world be different?",
    "Next, the vowel friends (ㅏ, ㅓ, ㅗ…) might wake up. What story would they tell?"
  ],
  gloss:{
    "쌔근쌔근":{ read:"쌔근쌔근", mean:"어린아이가 곤히 자며 숨 쉬는 모양", mean_en:"the soft sound of a baby breathing while sleeping peacefully" },
    "들썩":{ read:"들썩", mean:"무언가가 가볍게 위로 움직이는 모양", mean_en:"bobbing or lifting slightly; a small upward movement" },
    "들썩였어요":{ read:"들써겼어요", mean:"무언가가 가볍게 위로 움직였어요", mean_en:"moved slightly upward; wobbled or lifted a little" },
    "부스스":{ read:"부스스", mean:"잠에서 막 깨어 부스러기처럼 일어나는 모양", mean_en:"looking messy and sleepy just after waking up" },
    "기지개":{ read:"기지개", mean:"팔다리를 쭉 펴며 몸을 늘이는 동작", mean_en:"a stretch; spreading arms and legs wide to wake the body up" },
    "까르르":{ read:"까르르", mean:"아이들이 크고 맑게 웃는 소리", mean_en:"the bright giggling sound children make when laughing out loud" },
    "덜컹덜컹":{ read:"덜컹덜컹", mean:"문이나 물건이 흔들리며 나는 소리", mean_en:"a rattling or clanking sound of a door or object shaking" },
    "우르르":{ read:"우르르", mean:"여럿이 한꺼번에 몰려나오는 모양", mean_en:"a crowd rushing or tumbling out all at once" },
    "구불구불":{ read:"구불구불", mean:"이리저리 굽어 있는 모양", mean_en:"winding and curving in many directions; wiggly" },
    "랄랄라":{ read:"랄랄라", mean:"가볍게 흥얼거리는 노랫소리", mean_en:"la-la-la; a light humming or singing sound" },
    "데굴데굴":{ read:"데굴데굴", mean:"동그란 것이 계속 구르는 모양", mean_en:"rolling around and around; the way a ball keeps rolling" },
    "삐뚤빼뚤":{ read:"삐뚤빼뚤", mean:"줄이 곧지 않고 비뚜름한 모양", mean_en:"crooked and uneven; not in a straight line" },
    "살금살금":{ read:"살금살금", mean:"소리 나지 않게 조심히 움직이는 모양", mean_en:"moving very quietly and carefully so no one hears; tiptoeing" },
    "반짝반짝":{ read:"반짝반짝", mean:"작은 빛이 자꾸 빛나는 모양", mean_en:"sparkling or twinkling with small flashes of light" },
    "빙긋":{ read:"빙귿", mean:"소리 없이 입가만 살짝 웃는 모양", mean_en:"a small quiet smile; smiling gently without making a sound" },
    "우뚝":{ read:"우뚝", mean:"하나가 높이 솟아 있는 모양", mean_en:"standing tall and upright above everything else" },
    "깜깜":{ read:"깜깜", mean:"빛이 전혀 없어 아주 어두운 모양", mean_en:"completely dark with no light at all" },
    "밤":{ read:"밤", mean:"해가 지고 어두운 시간", mean_en:"night; the dark time after the sun goes down" },
    "도서관":{ read:"도서관", mean:"책이 많이 있어서 빌려볼 수 있는 곳", mean_en:"a library; a place with many books you can read or borrow" },
    "잠":{ read:"잠", mean:"눈을 감고 쉬는 것", mean_en:"sleep; closing your eyes to rest" },
    "책장":{ read:"책장", mean:"책을 꽂아 두는 선반", mean_en:"a bookshelf; a shelf for keeping books" },
    "먼지":{ read:"먼지", mean:"공기 중에 떠다니는 아주 작은 티끌", mean_en:"dust; tiny particles that float in the air and settle on things" },
    "상자":{ read:"상자", mean:"물건을 담는 네모난 통", mean_en:"a box; a square container for putting things inside" },
    "살짝":{ read:"살짝", mean:"아주 조금, 부드럽게", mean_en:"just a little; very gently and slightly" },
    "처음":{ read:"처음", mean:"맨 앞, 시작 부분", mean_en:"the very first; the beginning" },
    "눈":{ read:"눈", mean:"볼 수 있게 해 주는 얼굴의 기관", mean_en:"eyes; the part of the face used for seeing" },
    "둥글게":{ read:"둥글게", mean:"동그란 모양으로", mean_en:"in a round circle shape" },
    "굽은":{ read:"구분", mean:"구부러진, 휘어진", mean_en:"bent or curved; not straight" },
    "이름":{ read:"이름", mean:"사람이나 물건을 부르는 말", mean_en:"a name; the word used to call a person or thing" },
    "기역":{ read:"기역", mean:"한글 자음 중 첫 번째 글자 ㄱ의 이름", mean_en:"the name of the first Korean consonant letter G" },
    "콕":{ read:"콕", mean:"작고 뾰족한 것으로 살짝 찌르는 모양", mean_en:"a small sharp poke; jabbing with a pointed tip" },
    "찌르다":{ read:"찌르다", mean:"뾰족한 것으로 세게 대다", mean_en:"to poke or stab with something pointed" },
    "옆":{ read:"옆", mean:"바로 곁, 가까운 쪽", mean_en:"the side; right next to something" },
    "니은":{ read:"니은", mean:"한글 자음 중 두 번째 글자 ㄴ의 이름", mean_en:"the name of the second Korean consonant letter N" },
    "폭신":{ read:"폭신", mean:"부드럽고 눌리는 느낌", mean_en:"soft and squishy; comfortable to lie on" },
    "침대":{ read:"침대", mean:"누워서 자는 가구", mean_en:"a bed; furniture for sleeping on" },
    "길게":{ read:"길게", mean:"길이가 늘어나도록", mean_en:"for a long time; stretched out long" },
    "손":{ read:"손", mean:"팔 끝에 있는, 물건을 잡는 신체 부위", mean_en:"a hand; the body part at the end of the arm used for grabbing" },
    "잡다":{ read:"잡다", mean:"손으로 꽉 쥐다", mean_en:"to grab or hold with the hand" },
    "작은":{ read:"자근", mean:"크기가 적은", mean_en:"small; little in size" },
    "소리":{ read:"소리", mean:"귀로 들을 수 있는 것", mean_en:"sound; something you can hear with your ears" },
    "말":{ read:"말", mean:"생각을 표현하는 낱말이나 문장", mean_en:"a word or language; sounds that express thoughts" },
    "붙다":{ read:"붙다", mean:"서로 달라붙어 하나가 되다", mean_en:"to stick together; to join and become one" },
    "둘":{ read:"둘", mean:"숫자 2", mean_en:"two; the number 2" },
    "웃다":{ read:"웃다", mean:"기분이 좋아 입이 벌어지는 것", mean_en:"to laugh or smile; showing happiness with your face" },
    "문":{ read:"문", mean:"열고 닫을 수 있는 입구", mean_en:"a door; an opening that can be opened and closed" },
    "열리다":{ read:"열리다", mean:"닫혀 있던 것이 벌어지다", mean_en:"to open; when something closed becomes open" },
    "디귿":{ read:"디귿", mean:"한글 자음 중 세 번째 글자 ㄷ의 이름", mean_en:"the name of the third Korean consonant D" },
    "한쪽":{ read:"한쪽", mean:"한 방향, 한 면", mean_en:"one side; one direction" },
    "활짝":{ read:"활짝", mean:"가득 열리거나 피어 있는 모양", mean_en:"wide open; fully open or bloomed" },
    "춤추듯":{ read:"춤추듯", mean:"춤을 추는 것처럼", mean_en:"as if dancing; moving like a dancer" },
    "리을":{ read:"리을", mean:"한글 자음 중 네 번째 글자 ㄹ의 이름", mean_en:"the name of the fourth Korean consonant R/L" },
    "노래":{ read:"노래", mean:"목소리로 부르는 음악", mean_en:"a song; music you sing with your voice" },
    "좋아하다":{ read:"조아하다", mean:"마음에 들어 즐기다", mean_en:"to like; to enjoy something" },
    "노랫소리":{ read:"노랫소리", mean:"노래하는 소리", mean_en:"the sound of singing; a singing voice" },
    "퍼지다":{ read:"퍼지다", mean:"사방으로 넓게 번지다", mean_en:"to spread out; to reach in all directions" },
    "네모난":{ read:"네모난", mean:"사각형 모양의", mean_en:"square-shaped; having four equal sides" },
    "미음":{ read:"미음", mean:"한글 자음 ㅁ의 이름", mean_en:"the name of the Korean consonant M" },
    "입":{ read:"입", mean:"먹고 말하는 얼굴의 기관", mean_en:"a mouth; the part of the face used for eating and talking" },
    "야무지다":{ read:"야무지다", mean:"단단하고 빈틈이 없다", mean_en:"firm and tight; neat and sturdy with no gaps" },
    "주머니":{ read:"주머니", mean:"물건을 넣는 작은 자루나 포켓", mean_en:"a pocket or small pouch for holding things" },
    "닮다":{ read:"닮다", mean:"모양이나 성질이 비슷하다", mean_en:"to resemble; to look similar to something" },
    "비읍":{ read:"비읍", mean:"한글 자음 ㅂ의 이름", mean_en:"the name of the Korean consonant B/P" },
    "보물":{ read:"보물", mean:"아주 소중하고 값진 물건", mean_en:"treasure; something very precious and valuable" },
    "담다":{ read:"담다", mean:"그릇이나 공간에 넣다", mean_en:"to put inside; to fill a container with something" },
    "뾰족한":{ read:"뾰족한", mean:"끝이 날카롭게 뾰족한", mean_en:"pointy; sharp at the tip" },
    "시옷":{ read:"시옷", mean:"한글 자음 ㅅ의 이름", mean_en:"the name of the Korean consonant S" },
    "산":{ read:"산", mean:"땅이 높이 솟은 곳", mean_en:"a mountain; a high area of land" },
    "서다":{ read:"서다", mean:"똑바로 일어서 있다", mean_en:"to stand; to be upright on your feet" },
    "동그란":{ read:"동그란", mean:"원 모양의, 둥근", mean_en:"round and circular in shape" },
    "이응":{ read:"이응", mean:"한글 자음 ㅇ의 이름", mean_en:"the name of the Korean consonant ng/silent" },
    "굴러오다":{ read:"굴러오다", mean:"구르면서 이쪽으로 오다", mean_en:"to roll toward; to come by rolling" },
    "아무":{ read:"아무", mean:"어느 누구, 어느 것이든", mean_en:"any; no particular one" },
    "자리":{ read:"자리", mean:"있어야 할 장소나 위치", mean_en:"a place or spot; where something belongs" },
    "지키다":{ read:"지키다", mean:"자리나 약속을 잘 유지하다", mean_en:"to keep or guard; to stay in a place or honor a promise" },
    "품":{ read:"품", mean:"가슴에 끌어안은 공간", mean_en:"an embrace; the space in someone's arms or chest" },
    "시작하다":{ read:"시작하다", mean:"처음으로 무언가를 하기 시작하다", mean_en:"to start; to begin something for the first time" },
    "남은":{ read:"남은", mean:"아직 남아 있는", mean_en:"remaining; still left over" },
    "줄줄이":{ read:"줄줄이", mean:"차례대로 이어서", mean_en:"one after another in a line; in a row" },
    "깨어나다":{ read:"깨어나다", mean:"잠에서 깨어 정신이 들다", mean_en:"to wake up; to become awake after sleeping" },
    "인사":{ read:"인사", mean:"만날 때 예를 갖추어 하는 행동이나 말", mean_en:"a greeting; what you say or do when you meet someone" },
    "이제":{ read:"이제", mean:"지금부터, 바로 지금", mean_en:"now; from this moment on" },
    "자음":{ read:"자음", mean:"모음과 함께 쓰는 한글 낱자(ㄱㄴㄷ…)", mean_en:"a consonant; a letter like G, N, D in the Korean alphabet" },
    "모두":{ read:"모두", mean:"빠짐없이 전부", mean_en:"all; everyone or everything without exception" },
    "모이다":{ read:"모이다", mean:"한곳에 다 함께 오다", mean_en:"to gather; to come together in one place" },
    "울먹이다":{ read:"울머기다", mean:"울 것 같아서 목소리가 떨리다", mean_en:"to be on the verge of crying; voice trembling as if about to cry" },
    "서로":{ read:"서로", mean:"둘 이상이 함께, 양쪽이 다", mean_en:"each other; both sides together" },
    "얼굴":{ read:"얼굴", mean:"눈·코·입이 있는 머리 앞면", mean_en:"a face; the front of the head with eyes, nose, and mouth" },
    "바라보다":{ read:"바라보다", mean:"멀리서 눈을 향해 보다", mean_en:"to look at; to gaze at something or someone" },
    "그때":{ read:"그때", mean:"바로 그 순간", mean_en:"at that moment; just then" },
    "창가":{ read:"창가", mean:"창문 가까이", mean_en:"near the window; by the window" },
    "가리키다":{ read:"가리키다", mean:"손가락으로 방향을 알리다", mean_en:"to point at; to show the direction with a finger" },
    "글자":{ read:"글자", mean:"말을 적기 위한 문자", mean_en:"a letter or character; a written symbol for language" },
    "배우다":{ read:"배우다", mean:"새로운 것을 공부해서 알게 되다", mean_en:"to learn; to study and come to know something new" },
    "아이":{ read:"아이", mean:"어린 사람, 어린이", mean_en:"a child; a young person" },
    "공책":{ read:"공책", mean:"글씨를 쓰는 종이 묶음", mean_en:"a notebook; a book of blank pages for writing" },
    "쓰다":{ read:"쓰다", mean:"연필이나 펜으로 글자를 남기다", mean_en:"to write; to make letters with a pencil or pen" },
    "가득":{ read:"가득", mean:"꽉 채워진 상태", mean_en:"full; filled to the top with no space left" },
    "빈":{ read:"빈", mean:"아무것도 없는, 텅 빈", mean_en:"empty; having nothing inside" },
    "칸":{ read:"칸", mean:"나누어진 작은 공간", mean_en:"a section or cell; a small divided space" },
    "하나둘":{ read:"하나둘", mean:"하나씩 둘씩, 조금씩", mean_en:"one by one; little by little" },
    "채워지다":{ read:"채워지다", mean:"빈 곳이 다 메워지다", mean_en:"to be filled in; when empty spaces get completed" },
    "아침":{ read:"아침", mean:"하루가 시작되는 이른 시간", mean_en:"morning; the early part of the day when it starts" },
    "햇살":{ read:"핻쌀", mean:"해가 내리쬐는 빛", mean_en:"sunlight; the warm bright light from the sun" },
    "손가락":{ read:"손가락", mean:"손 끝의 다섯 개 마디", mean_en:"a finger; one of the five parts at the end of the hand" },
    "짚다":{ read:"짚다", mean:"손가락으로 콕 눌러 가리키다", mean_en:"to point at or tap; to press a finger on something to show it" },
    "읽다":{ read:"읽다", mean:"글자를 보며 소리나 뜻을 파악하다", mean_en:"to read; to look at words and understand their meaning" },
    "마음속":{ read:"마음속", mean:"마음의 안쪽", mean_en:"inside the heart or mind; deep in one's feelings" },
    "조용히":{ read:"조용히", mean:"소리 없이 가만히", mean_en:"quietly; without making any noise" },
    "따라 읽다":{ read:"따라읽다", mean:"다른 사람을 흉내 내어 같이 읽다", mean_en:"to read along; to copy someone and read the same thing" },
    "책":{ read:"책", mean:"여러 장의 종이를 묶은 읽을거리", mean_en:"a book; sheets of paper bound together with words to read" },
    "돌아가다":{ read:"돌아가다", mean:"있던 곳으로 다시 가다", mean_en:"to go back; to return to where you were before" },
    "언제든":{ read:"언제든", mean:"어느 때든지", mean_en:"anytime; whenever you want" },
    "부르다":{ read:"부르다", mean:"이름이나 소리로 누군가를 불러 오게 하다", mean_en:"to call out; to say someone's name so they come" },
    "준비":{ read:"준비", mean:"미리 갖추어 두는 것", mean_en:"preparation; getting ready in advance" },
    "차례":{ read:"차례", mean:"순서가 돌아올 때", mean_en:"one's turn; the moment when it is your time to go" },
    "천천히":{ read:"천천히", mean:"빠르지 않게 느리게", mean_en:"slowly; not fast; at a gentle pace" },
    "또":{ read:"또", mean:"다시 한 번 더", mean_en:"again; one more time" },
    "함께":{ read:"함께", mean:"같이, 둘 이상이 모여서", mean_en:"together; with each other" },
    "고요하다":{ read:"고요하다", mean:"아무 소리 없이 조용하다", mean_en:"quiet and still; very peaceful with no noise" },
    "쏟아지다":{ read:"쏟아지다", mean:"한꺼번에 많이 쏟아져 나오다", mean_en:"to pour out; to come out all at once in a rush" },
    "퍼지다":{ read:"퍼지다", mean:"사방으로 넓게 번지다", mean_en:"to spread; to move outward in all directions" },
    "알다":{ read:"알다", mean:"모르던 것을 이해하거나 기억하다", mean_en:"to know; to understand or remember something" },
    "가다":{ read:"가다", mean:"어딘가로 움직이다", mean_en:"to go; to move toward a place" },
    "오다":{ read:"오다", mean:"이쪽으로 움직여 오다", mean_en:"to come; to move toward here" },
    "있다":{ read:"있다", mean:"어떤 곳에 존재하다", mean_en:"to be; to exist or to be in a place" },
    "없이":{ read:"업씨", mean:"무언가가 없는 상태로", mean_en:"without; in the absence of something" },
    "작다":{ read:"작다", mean:"크기가 크지 않다", mean_en:"small; not big in size" },
    "생기다":{ read:"생기다", mean:"모양이 어떻게 생겼다, 나타나다", mean_en:"to look like; to have a certain shape or appearance" },

    "자":{ read:"자", mean:"눈을 감고 쉬다 (자다)", mean_en:"to sleep; to close your eyes and rest" },
    "뜨":{ read:"뜨", mean:"눈을 열다 (눈을 뜨다)", mean_en:"to open eyes; to lift eyelids and wake up" },
    "일어나":{ read:"일어나", mean:"누워 있다가 몸을 일으키다", mean_en:"to get up; to rise from lying or sitting" },
    "길":{ read:"길", mean:"짧지 않고 길이가 길다", mean_en:"long; having great length" },
    "나":{ read:"나", mean:"소리나 현상이 생기다 (소리가 나다)", mean_en:"to occur; to come out (as a sound or event)" },
    "웃":{ read:"웃", mean:"기쁨이나 즐거움으로 웃다", mean_en:"to laugh or smile; to show happiness" },
    "나오":{ read:"나오", mean:"안에서 밖으로 오다", mean_en:"to come out; to move from inside to outside" },
    "열":{ read:"열", mean:"닫힌 것을 열다 (능동)", mean_en:"to open something; to make something open" },
    "인사하":{ read:"인사하", mean:"만남이나 헤어짐에 예를 갖추다", mean_en:"to greet; to say hello or goodbye politely" },
    "잠들":{ read:"잠들", mean:"잠이 들어 자기 시작하다", mean_en:"to fall asleep; to begin sleeping" },
    "채우":{ read:"채우", mean:"빈 곳을 가득 메우다", mean_en:"to fill up; to make something full" },
    "동그랗":{ read:"동그랗", mean:"둥근 원 모양이다", mean_en:"to be round and circular in shape" },
    "둥글":{ read:"둥글", mean:"모가 없이 둥근 모양이다", mean_en:"rounded; having a smooth curved shape with no sharp edges" },
    "작":{ read:"작", mean:"크기가 크지 않다", mean_en:"small; little; not big" },
    "크":{ read:"크", mean:"크기나 범위가 많다", mean_en:"big; large in size" },
    "폭신":{ read:"폭신", mean:"부드럽고 쿠션처럼 푹 꺼지는 느낌", mean_en:"soft and cushiony; squishy and comfortable" },
    "뾰족":{ read:"뾰족", mean:"끝이 날카롭고 뾰족하다", mean_en:"pointy; sharp and narrow at the tip" },
    "네모":{ read:"네모", mean:"사각형 모양이다", mean_en:"square; having four straight sides" },
    "켜":{ read:"켜", mean:"기지개처럼 몸을 쭉 늘이다", mean_en:"to stretch; to extend the body by pulling it long" },
    "춤추":{ read:"춤추", mean:"음악에 맞춰 몸을 움직이다", mean_en:"to dance; to move the body to music" },
    "없다":{ read:"없다", mean:"어떤 것이 존재하지 않다", mean_en:"to not exist; to be absent; there is none" },
    "가득하":{ read:"가득하", mean:"꽉 차 있는 상태이다", mean_en:"to be full; to be completely filled with something" },
    "들":{ read:"들", mean:"잠이 들다 — 잠에 빠져들다", mean_en:"to fall into sleep; to drift off to sleep" },

    "맨":{ read:"맨", mean:"가장, 제일 (맨 끝, 맨 처음)", mean_en:"the very; the most (as in the very first, the very end)" },
    "끝":{ read:"끝", mean:"마지막 부분, 제일 뒤쪽", mean_en:"the end; the last part of something" },
    "쌓":{ read:"쌓", mean:"물건이 위로 겹겹이 올려진 상태", mean_en:"piled up; stacked one on top of another" },
    "하나":{ read:"하나", mean:"숫자 1, 한 개", mean_en:"one; the number 1; a single thing" },
    "잘":{ read:"잘", mean:"훌륭하게, 충분히, 제대로", mean_en:"well; properly; in a good way" },
    "뭐":{ read:"뭐", mean:"무엇 (구어체)", mean_en:"what; the spoken short form of 무엇" },
    "기윽":{ read:"기윽", mean:"ㄱ을 읽을 때 나는 소리 이름", mean_en:"the sound name of the consonant ㄱ before it was officially named Giyeok" },
    "때":{ read:"때", mean:"어떤 일이 일어나는 시점이나 순간", mean_en:"a time; a moment when something happens" },
    "눕":{ read:"눕", mean:"몸을 가로로 뉘이다, 드러눕다", mean_en:"to lie down; to put the body flat" },
    "우리":{ read:"우리", mean:"나와 함께하는 사람들, 나+남", mean_en:"we; us; me and the others together" },
    "되":{ read:"되", mean:"무언가로 변하거나 이루어지다 (되다)", mean_en:"to become; to turn into something" },
    "지읒":{ read:"지읒", mean:"한글 자음 ㅈ의 이름", mean_en:"the name of the Korean consonant J" },
    "치읓":{ read:"치읓", mean:"한글 자음 ㅊ의 이름", mean_en:"the name of the Korean consonant Ch" },
    "키읔":{ read:"키읔", mean:"한글 자음 ㅋ의 이름", mean_en:"the name of the Korean consonant K" },
    "티읕":{ read:"티읕", mean:"한글 자음 ㅌ의 이름", mean_en:"the name of the Korean consonant T" },
    "피읖":{ read:"피읖", mean:"한글 자음 ㅍ의 이름", mean_en:"the name of the Korean consonant P/F" },
    "히읗":{ read:"히읗", mean:"한글 자음 ㅎ의 이름", mean_en:"the name of the Korean consonant H" },
    "그런데":{ read:"그런데", mean:"앞 말에 이어 다른 내용을 말할 때 쓰는 말", mean_en:"but; however; used when adding something unexpected" },
    "어디":{ read:"어디", mean:"무슨 장소, 어느 곳", mean_en:"where; which place" },
    "저기":{ read:"저기", mean:"말하는 사람에게서 먼 곳", mean_en:"over there; a place far from the speaker" },
    "쏙":{ read:"쏙", mean:"좁은 곳에 깔끔하게 들어가는 모양", mean_en:"snugly fitting in; sliding neatly into a tight space" },
    "다":{ read:"다", mean:"모두, 전부 빠짐없이 (다 채워졌네)", mean_en:"all; completely; every bit of it" },
    "같":{ read:"같", mean:"다른 것과 비슷해 보이다 (같다)", mean_en:"to seem like; to look similar to something" },
    "이번":{ read:"이번", mean:"지금 이 순서, 지금 이때", mean_en:"this time; this particular turn or occasion" },
    "보":{ read:"보", mean:"눈으로 살펴보다 (보다)", mean_en:"to look; to see with one's eyes" },
    "친구":{ read:"친구", mean:"사이 좋게 지내는 사람", mean_en:"a friend; someone you like and spend time with" },
    "다시":{ read:"다시", mean:"한 번 더, 새로 다시", mean_en:"again; one more time; starting over" },
    "속":{ read:"속", mean:"무언가의 안쪽, 내부", mean_en:"inside; the inner part of something" },
    "그래도":{ read:"그래도", mean:"그렇더라도, 그럼에도 불구하고", mean_en:"even so; still; despite that" },
    "첫":{ read:"첫", mean:"맨 처음의, 순서상 제일 앞의", mean_en:"the first; coming before all others" },
    "번째":{ read:"번째", mean:"순서를 나타내는 말 (첫 번째, 두 번째)", mean_en:"the -th; a word showing order (first, second...)" },
    "만들":{ read:"만들", mean:"재료나 힘을 써서 새로운 것을 이루다", mean_en:"to make; to create something new" },
    "든든하":{ read:"든든하", mean:"믿음직스럽고 튼튼한", mean_en:"sturdy and reliable; strong enough to be trusted" },
    "마지막":{ read:"마지막", mean:"순서나 시간의 제일 끝", mean_en:"the last; the final one in order or time" },
    "이야기":{ read:"이야기", mean:"일어난 일이나 생각을 말하거나 쓴 것", mean_en:"a story; telling about something that happened or was imagined" },
    "책상":{ read:"책상", mean:"책이나 공부 도구를 올려두고 공부하는 상", mean_en:"a desk; a table for studying or reading" },
    "살며시":{ read:"살며시", mean:"소리 없이 아주 조심스럽게", mean_en:"very gently and quietly; so softly no one notices" },
    "글":{ read:"글", mean:"말을 글자로 적어 놓은 것", mean_en:"writing; words written down with letters" },
    "해":{ read:"해", mean:"하늘에서 빛을 내는 태양", mean_en:"the sun; the bright star in the sky that gives us light" },
    "빛":{ read:"빛", mean:"눈으로 볼 수 있게 하는 밝은 에너지", mean_en:"light; the bright energy that lets us see things" },
    "잃어버리":{ read:"잃어버리", mean:"가지고 있던 것을 찾지 못하게 되다", mean_en:"to lose; to no longer be able to find something" },
    "너":{ read:"너", mean:"말하는 상대방을 가리키는 말", mean_en:"you; the person being spoken to" },
    "모양":{ read:"모양", mean:"사물의 생김새나 형태", mean_en:"a shape; the way something looks or is formed" },
    "반짝":{ read:"반짝", mean:"빛이 순간적으로 밝게 빛나다", mean_en:"to flash or sparkle briefly" },
    "나타나":{ read:"나타나", mean:"보이지 않던 것이 눈에 보이게 되다", mean_en:"to appear; to show up where it could not be seen before" },
    "지우":{ read:"지우", mean:"쓰거나 그린 것을 없애다", mean_en:"to erase; to remove what was written or drawn" },
    "깊":{ read:"깊", mean:"아래나 안쪽으로 많이 들어간", mean_en:"deep; going far down or far inside" },
    "부드럽":{ read:"부드럽", mean:"딱딱하지 않고 보드랍다", mean_en:"soft; gentle; not hard or rough" },
    "새":{ read:"새", mean:"전에 없던 것, 처음 생긴 것", mean_en:"new; something that did not exist before" },
    "세상":{ read:"세상", mean:"우리가 사는 지구와 모든 것", mean_en:"the world; all the people and things around us" },
    "어":{ read:"어", mean:"놀라거나 의아할 때 내는 소리", mean_en:"huh; oh; a sound made when surprised or puzzled" },
    "으으":{ read:"으으", mean:"잠에서 막 깨어날 때 내는 소리", mean_en:"a groan or grunt made when just waking up" },
    "쌔근":{ read:"쌔근", mean:"곤히 잠들어 고르게 숨 쉬는 소리의 단위", mean_en:"the gentle, even breathing sound of deep sleep" },
    "눈을 뜨":{ read:"눈을 뜨", mean:"눈꺼풀을 올려 눈을 열다", mean_en:"to open the eyes; to lift the eyelids" },
    "일어나다":{ read:"일어나다", mean:"잠자거나 앉아 있다가 몸을 세우다", mean_en:"to get up; to rise from lying or sitting down" },
    "쭉":{ read:"쭉", mean:"한 방향으로 힘껏 길게 뻗는 모양", mean_en:"stretching straight out with force; all the way out" },
    "가볍":{ read:"가볍", mean:"무게가 적고 다루기 쉽다", mean_en:"light; not heavy; easy to lift or move" },
    "작은 소리":{ read:"작은 소리", mean:"크지 않은, 살짝 들리는 소리", mean_en:"a small sound; a noise that is just barely heard" },
    "울먹":{ read:"울먹", mean:"울 것 같아 목소리가 떨리는 모양", mean_en:"on the verge of tears; voice shaking as if about to cry" },
    "반드시":{ read:"반드시", mean:"꼭, 틀림없이", mean_en:"surely; without fail; definitely" },
    "나란히":{ read:"나란히", mean:"옆으로 줄지어 나란하게", mean_en:"side by side; lined up next to each other" },
    "부스":{ read:"부스", mean:"잠에서 깨어 정신이 아직 멍한 모양", mean_en:"groggy; the dazed feeling right after waking up" },
    "사방":{ read:"사방", mean:"동서남북 모든 방향", mean_en:"all four directions; everywhere around" },
    "활":{ read:"활", mean:"크게 열린 모양 (활짝의 어간)", mean_en:"wide open; spread out fully (root of 활짝)" },
    "조심":{ read:"조심", mean:"다치거나 실수하지 않게 주의하는 것", mean_en:"caution; being careful not to make a mistake or get hurt" }
  },
  gloss_en:{
    "library":{ read:"library", mean:"a place full of books you can read or borrow", mean_ko:"도서관 — 책을 읽거나 빌릴 수 있는 곳" },
    "shelf":{ read:"shelf", mean:"a flat board on a wall where you keep books or things", mean_ko:"선반, 책장 — 책이나 물건을 올려 두는 칸" },
    "dusty":{ read:"dusty", mean:"covered with dust; not cleaned for a long time", mean_ko:"먼지가 쌓인 — 오래 청소하지 않은" },
    "box":{ read:"box", mean:"a square container for keeping things inside", mean_ko:"상자 — 물건을 담는 네모난 통" },
    "shake":{ read:"shake", mean:"to move quickly back and forth or up and down", mean_ko:"흔들다, 흔들리다 — 빠르게 움직이다" },
    "asleep":{ read:"asleep", mean:"sleeping; with eyes closed and resting", mean_ko:"잠든 — 눈을 감고 자고 있는" },
    "wake up":{ read:"wake up", mean:"to stop sleeping and open your eyes", mean_ko:"깨어나다 — 잠에서 깨어 눈을 뜨다" },
    "letter":{ read:"letter", mean:"a written symbol used to make words, like A or ㄱ", mean_ko:"글자, 낱자 — 말을 적는 문자 (A, ㄱ 등)" },
    "consonant":{ read:"consonant", mean:"a letter that is not a vowel, like g, n, d, m", mean_ko:"자음 — 모음이 아닌 글자 (ㄱ, ㄴ, ㄷ…)" },
    "vowel":{ read:"vowel", mean:"a letter like a, e, i, o, u that opens the mouth", mean_ko:"모음 — ㅏ, ㅓ, ㅗ 처럼 입을 여는 글자" },
    "sound":{ read:"sound", mean:"something you can hear with your ears", mean_ko:"소리 — 귀로 들을 수 있는 것" },
    "name":{ read:"name", mean:"the word used to call a person or thing", mean_ko:"이름 — 사람이나 물건을 부르는 말" },
    "shape":{ read:"shape", mean:"the form of something — round, square, pointy", mean_ko:"모양 — 둥글거나 네모나거나 뾰족한 형태" },
    "hook":{ read:"hook", mean:"a bent piece used to hang or hold things", mean_ko:"갈고리 — 구부러져 무언가를 거는 물건" },
    "bent":{ read:"bent", mean:"curved; not straight", mean_ko:"굽은 — 휘어져 곧지 않은" },
    "poke":{ read:"poke", mean:"to push someone gently with a finger", mean_ko:"콕 찌르다 — 손가락으로 살짝 밀다" },
    "sleepy":{ read:"sleepy", mean:"feeling tired and wanting to sleep", mean_ko:"졸린 — 자고 싶을 만큼 피곤한" },
    "stretch":{ read:"stretch", mean:"to reach out your arms and legs to wake your body", mean_ko:"기지개를 켜다 — 팔다리를 쭉 펴다" },
    "comfy":{ read:"comfy", mean:"soft and comfortable", mean_ko:"폭신한, 편안한 — 부드럽고 편한" },
    "bed":{ read:"bed", mean:"furniture you lie on to sleep", mean_ko:"침대 — 누워서 자는 가구" },
    "hold hands":{ read:"hold hands", mean:"to join your hand with another's", mean_ko:"손을 잡다 — 서로 손을 마주 잡다" },
    "word":{ read:"word", mean:"sounds or letters that mean something together", mean_ko:"낱말, 말 — 뜻을 가진 소리나 글자" },
    "giggle":{ read:"giggle", mean:"to laugh in a soft, happy, bubbly way", mean_ko:"까르르 웃다 — 가볍고 즐겁게 웃다" },
    "door":{ read:"door", mean:"a part you open and close to go in or out", mean_ko:"문 — 열고 닫는 입구" },
    "open":{ read:"open", mean:"to move something so it is no longer closed", mean_ko:"열다, 열리다 — 닫힌 것을 벌리다" },
    "rattle":{ read:"rattle", mean:"a noisy, shaky sound like a door moving", mean_ko:"덜컹 소리 — 흔들리며 나는 시끄러운 소리" },
    "tumble":{ read:"tumble", mean:"to fall or roll out suddenly", mean_ko:"우르르 쏟아지다 — 갑자기 굴러 나오다" },
    "wiggly":{ read:"wiggly", mean:"moving with little curvy wiggles; not straight", mean_ko:"구불구불한 — 이리저리 휘어진" },
    "dancing":{ read:"dancing", mean:"moving your body to music", mean_ko:"춤추는 — 음악에 맞춰 몸을 움직이는" },
    "float":{ read:"float", mean:"to move gently in the air", mean_ko:"떠다니다, 퍼지다 — 공중을 부드럽게 움직이다" },
    "square":{ read:"square", mean:"a shape with four equal straight sides", mean_ko:"네모, 정사각형 — 네 변이 같은 모양" },
    "tidy":{ read:"tidy", mean:"neat and in good order", mean_ko:"야무진, 깔끔한 — 정돈된" },
    "mouth":{ read:"mouth", mean:"the part of your face you eat and talk with", mean_ko:"입 — 먹고 말하는 얼굴 부위" },
    "pocket":{ read:"pocket", mean:"a small bag in clothes for holding things", mean_ko:"주머니 — 물건을 넣는 작은 자루" },
    "treasure":{ read:"treasure", mean:"something very special and valuable", mean_ko:"보물 — 아주 소중한 것" },
    "pointy":{ read:"pointy", mean:"having a sharp point at the end", mean_ko:"뾰족한 — 끝이 날카로운" },
    "mountain":{ read:"mountain", mean:"a very high piece of land", mean_ko:"산 — 아주 높이 솟은 땅" },
    "tall":{ read:"tall", mean:"high; reaching far up", mean_ko:"키 큰, 높은 — 위로 길게 솟은" },
    "round":{ read:"round", mean:"shaped like a circle or ball", mean_ko:"동그란 — 원이나 공 모양의" },
    "roll":{ read:"roll", mean:"to move by turning over and over", mean_ko:"구르다 — 데굴데굴 돌며 움직이다" },
    "quiet":{ read:"quiet", mean:"making little or no sound", mean_ko:"조용한 — 소리가 거의 없는" },
    "begin":{ read:"begin", mean:"to start something", mean_ko:"시작하다 — 처음으로 무언가를 하다" },
    "window":{ read:"window", mean:"a glass opening in a wall to see outside", mean_ko:"창문 — 밖을 보는 유리 구멍" },
    "point":{ read:"point", mean:"to show where something is with your finger", mean_ko:"가리키다 — 손가락으로 위치를 알리다" },
    "child":{ read:"child", mean:"a young boy or girl", mean_ko:"아이, 어린이 — 어린 사람" },
    "notebook":{ read:"notebook", mean:"a book of blank pages for writing", mean_ko:"공책 — 글씨를 쓰는 빈 종이 묶음" },
    "wobbly":{ read:"wobbly", mean:"shaky and uneven; not steady or straight", mean_ko:"삐뚤빼뚤한 — 흔들려 곧지 않은" },
    "tiptoe":{ read:"tiptoe", mean:"to walk quietly on the tips of your toes", mean_ko:"살금살금 걷다 — 발끝으로 조용히 걷다" },
    "creep":{ read:"creep", mean:"to move slowly and quietly", mean_ko:"살며시 가다 — 천천히 조용히 움직이다" },
    "slip":{ read:"slip", mean:"to move smoothly and quietly into a place", mean_ko:"쏙 들어가다 — 부드럽게 자리에 들어가다" },
    "empty":{ read:"empty", mean:"having nothing inside", mean_ko:"빈 — 아무것도 없는" },
    "fill":{ read:"fill", mean:"to put something into an empty space until it is full", mean_ko:"채우다 — 빈 곳을 가득 메우다" },
    "sunlight":{ read:"sunlight", mean:"the bright warm light from the sun", mean_ko:"햇살 — 해의 밝고 따뜻한 빛" },
    "morning":{ read:"morning", mean:"the early part of the day", mean_ko:"아침 — 하루가 시작되는 이른 때" },
    "sparkle":{ read:"sparkle", mean:"to shine with small bright flashes of light", mean_ko:"반짝이다 — 작은 빛이 빛나다" },
    "smile":{ read:"smile", mean:"to make a happy face with your mouth", mean_ko:"미소 짓다 — 기뻐 입가가 올라가다" },
    "finger":{ read:"finger", mean:"one of the five parts at the end of your hand", mean_ko:"손가락 — 손 끝의 다섯 마디" },
    "tap":{ read:"tap", mean:"to touch something lightly and quickly", mean_ko:"콕 짚다, 톡 치다 — 가볍게 빠르게 대다" },
    "read along":{ read:"read along", mean:"to read at the same time as someone else", mean_ko:"따라 읽다 — 다른 사람과 같이 읽다" },
    "gentle":{ read:"gentle", mean:"soft, kind, and calm", mean_ko:"부드러운, 다정한 — 온화한" },
    "story":{ read:"story", mean:"a telling of things that happen, real or made up", mean_ko:"이야기 — 일어난 일이나 지어낸 일을 들려줌" },
    "turn":{ read:"turn", mean:"the time when it is your chance to do something", mean_ko:"차례 — 내가 할 순서" },
    "call":{ read:"call", mean:"to say a name loudly so someone comes", mean_ko:"부르다 — 이름을 외쳐 오게 하다" },
    "together":{ read:"together", mean:"with one another; as a group", mean_ko:"함께 — 같이, 여럿이 모여" }
  }
};
